const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

test('welcome screen is an IDE start surface instead of a marketing hero', () => {
  const shell = read('src/renderer/shell.js')
  const tabs = read('src/renderer/tabs.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(shell, /welcome__start/)
  assert.match(shell, /welcome__actions/)
  assert.match(shell, /welcome__workspace-panel/)
  assert.match(shell, /welcome__status-strip/)
  assert.doesNotMatch(shell, /welcome__hero-panel/)
  assert.doesNotMatch(shell, /welcome__aurora/)
  assert.doesNotMatch(shell, /welcome__mesh/)
  assert.doesNotMatch(css, /\.welcome__aurora/)
  assert.doesNotMatch(css, /\.welcome__mesh/)
  assert.doesNotMatch(css, /\.welcome::after/)
  assert.doesNotMatch(css, /\.welcome__title-row/)
  assert.match(css, /\.welcome__start/)
  assert.match(css, /\.welcome__actions/)
  assert.match(shell, /#welcome-open-btn, #welcome-new-file-btn/)
  assert.match(tabs, /welcome-new-file-btn/)
  assert.match(tabs, /welcome-new-file-btn'[\s\S]*addEventListener\('click', createNewFile\)/)
})

test("status bar collapsed to metrics and settings only", () => {
  const shell = read("src/renderer/shell.js")
  const css = read("src/renderer/styles/main.css")

  assert.match(shell, /statusbar__metrics/)
  assert.match(shell, /st-filename/)
  assert.match(shell, /st-words/)
  assert.match(shell, /st-readtime/)
  assert.match(shell, /st--mode/)
  assert.match(shell, /st-brand/)
  assert.match(shell, /id="settings-btn"/)
  assert.match(shell, /aria-label="Open settings"/)
  assert.doesNotMatch(shell, /aria-label="Toggle terminal"/)
  assert.doesNotMatch(shell, /aria-label="Toggle right widgets panel"/)
})
test('settings panel uses compact tabs and visual preset swatches', () => {
  const shell = read('src/renderer/shell.js')
  const settings = read('src/renderer/settings.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(shell, /settings-tabs/)
  assert.match(shell, /settings-preset-grid/)
  assert.match(shell, /settings-swatch/)
  assert.match(shell, /settings-advanced/)
  assert.match(shell, /Installed app font or stack/)
  assert.match(shell, /Installed editor font or stack/)
  assert.match(settings, /const PROPORTIONAL_FONT_OPTIONS/)
  assert.match(settings, /const MONO_FONT_OPTIONS/)
  assert.match(settings, /ui: PROPORTIONAL_FONT_OPTIONS/)
  assert.match(settings, /explorer: PROPORTIONAL_FONT_OPTIONS/)
  assert.match(settings, /preview: PROPORTIONAL_FONT_OPTIONS/)
  assert.match(settings, /editor: MONO_FONT_OPTIONS/)
  assert.doesNotMatch(settings, /Avenir \/ Segoe/)
  assert.doesNotMatch(settings, /Iowan \/ Palatino/)
  assert.match(css, /\.settings-page\.active/)
  assert.match(css, /\.settings-swatch/)
})

test('settings are organized as Markdown IDE preferences with custom font pickers', () => {
  const shell = read('src/renderer/shell.js')
  const settings = read('src/renderer/settings.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(shell, /\{ id: 'appearance', label: 'Appearance' \}/)
  assert.match(shell, /\{ id: 'typography', label: 'Typography' \}/)
  assert.match(shell, /\{ id: 'editor', label: 'Editor' \}/)
  assert.match(shell, /\{ id: 'workspace', label: 'Workspace' \}/)
  assert.match(shell, /\{ id: 'ai-tools', label: 'AI & Tools' \}/)
  assert.match(shell, /\{ id: 'shortcuts', label: 'Shortcuts' \}/)
  assert.match(shell, /function renderFontPicker/)
  assert.match(shell, /data-font-picker=/)
  assert.match(shell, /data-font-option=/)
  assert.match(shell, /settings-font-picker/)
  assert.match(shell, /\[\`\$\{fontSetting\}Custom\`\]: ''/)
  assert.match(shell, /fontOption\.closest\('\[data-font-picker\]'\)\?\.classList\.remove\('open'\)/)
  assert.match(shell, /if \(valueLabel\) valueLabel\.textContent = fontLabelFor\(key\)/)
  assert.match(shell, /if \(sample\) sample\.style\.fontFamily = value/)
  assert.doesNotMatch(shell, /renderSelectSetting\('uiFont'/)
  assert.doesNotMatch(shell, /renderSelectSetting\('editorFont'/)
  assert.match(settings, /assistantDock: 'hidden'/)
  assert.match(css, /\.settings-font-picker/)
  assert.match(css, /\.settings-font-option/)
  assert.match(css, /\.settings-section-title/)
})

test('settings exposes selectable Split Rune app icon variants', () => {
  const settings = read('src/renderer/settings.js')
  const shell = read('src/renderer/shell.js')
  const css = read('src/renderer/styles/main.css')
  const adapter = read('src/renderer/tauri-api.js')
  const tauriMain = read('src-tauri/src/main.rs')

  assert.match(settings, /APP_ICON_VARIANTS/)
  assert.match(settings, /appIconVariant: 'aurora-gradient'/)
  assert.match(settings, /appIconTheme: 'auto'/)
  assert.match(shell, /renderAppIconPicker/)
  assert.match(shell, /data-app-icon-variant/)
  assert.match(shell, /applySelectedAppIcon/)
  assert.match(css, /\.settings-icon-grid/)
  assert.match(adapter, /setAppIcon: \(variant, theme\) => invoke\('set_app_icon'/)
  assert.match(tauriMain, /fn set_app_icon/)
  assert.ok(fs.existsSync(path.join(root, 'public/logos/rista-split-rune-aurora-gradient-dark.svg')))
  assert.ok(fs.existsSync(path.join(root, 'src-tauri/icons/rista-split-rune-aurora-gradient-dark.png')))
})

test('macOS install copy verifies the bundled app icon', () => {
  const pkg = JSON.parse(read('package.json'))
  const installScript = read('scripts/install-macos-app.js')
  const fixScript = read('scripts/fix-macos-bundle-icon.js')

  assert.equal(pkg.scripts.package, 'tauri build --bundles app && node scripts/fix-macos-bundle-icon.js')
  assert.equal(pkg.scripts['install:mac'], 'node scripts/install-macos-app.js')
  assert.match(fixScript, /Rista\.icns/)
  assert.match(fixScript, /Rísta\.icns/)
  assert.match(fixScript, /Set :CFBundleIconFile/)
  assert.match(installScript, /Contents\/Resources\/Rista\.icns/)
  assert.match(installScript, /CFBundleIconFile/)
  assert.match(installScript, /assertBundleIcon\(sourceApp\)/)
  assert.match(installScript, /fs\.cpSync\(sourceApp, targetApp/)
  assert.match(installScript, /assertBundleIcon\(targetApp\)/)
})

test('split workspace has an actionable empty secondary pane', () => {
  const workspace = read('src/renderer/workspace.js')

  assert.match(workspace, /data-action="open-secondary-file"/)
  assert.match(workspace, /toggleCommandPalette/)
  assert.match(workspace, /state\.tabGroups\.secondary = \[\]/)
  assert.match(workspace, /state\.secondaryTab = null/)
})

test('workspace polish keeps split mode quiet, legible, and intentional', () => {
  const workspace = read('src/renderer/workspace.js')
  const settings = read('src/renderer/settings.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(workspace, /workspace-pane__empty-kicker/)
  assert.match(workspace, /Editor B is ready/)
  assert.match(settings, /contrastBoost: 22/)
  assert.match(css, /--hover-fill:/)
  assert.match(css, /--active-fill:/)
  assert.match(css, /--quiet-border:/)
  assert.match(css, /\.tree-file\.active\s*\{[\s\S]*font-weight: 600/)
  assert.match(css, /\.tab\.active\s*\{[\s\S]*border-color: var\(--active-border\)/)
  assert.match(css, /\.vb\.active\s*\{[\s\S]*box-shadow:[\s\S]*inset 0 0 0 1px var\(--active-border\)/)
  assert.match(css, /\.settings-group\s*\{[\s\S]*background: transparent/)
  assert.match(css, /\.settings-group\s*\{[\s\S]*border-top: 1px solid var\(--quiet-border\)/)
  assert.match(css, /\.app\[data-workspace-mode="dual"\] #workspace-secondary:has\(#tabs-secondary\.is-empty\) \.workspace-toolbar/)
  assert.match(css, /\.app\[data-workspace-mode="dual"\] \.workspace-resizer::before\s*\{[\s\S]*height: 48px/)
})

test('global and pane icon semantics stay distinct and labelled', () => {
  const icons = read('src/renderer/icons.js')
  const shell = read('src/renderer/shell.js')
  const workspace = read('src/renderer/workspace.js')

  assert.match(icons, /export function sidebarIcon/)
  assert.match(icons, /export function rightSidebarIcon/)
  assert.match(icons, /export function toolbarIcon/)
  assert.match(icons, /export function editorSplitIcon/)
  assert.match(icons, /export function workspaceSplitIcon/)
  assert.match(icons, /export function sunIcon/)
  assert.match(icons, /export function moonIcon/)
  // Statusbar collapsed to metrics + settings. Mode toggles live in Cmd-K only.
  assert.match(shell, /id="settings-btn"/)
  assert.match(shell, /aria-label="Open settings"/)
  assert.match(shell, /st-brand/)
  assert.doesNotMatch(shell, /aria-label="Toggle workspace split layout"/)
  assert.match(workspace, /title="Markdown source"/)
  assert.match(workspace, /title="Pane split preview"/)
  assert.match(workspace, /title="Rich text editor"/)
  assert.match(workspace, /title="Rendered preview"/)
  assert.match(workspace, /data-action="set-view" data-view="split"[^>]*aria-label="Pane split preview"/)
  assert.doesNotMatch(workspace, /data-action="toggle-workspace-split"/)
  assert.doesNotMatch(workspace, /id="pane-split-toggle"/)
})

test('programmatic editor document updates do not mark tabs dirty', () => {
  const editor = read('src/renderer/editor.js')

  assert.match(editor, /Annotation/)
  assert.match(editor, /programmaticDocUpdate/)
  assert.match(editor, /!isProgrammatic/)
  assert.match(editor, /annotations: programmaticDocUpdate\.of\(true\)/)
})

test('autosave delay follows settings instead of a hardcoded timer', () => {
  const tabs = read('src/renderer/tabs.js')

  assert.match(tabs, /getSettings\(\)\.autoSaveDelay/)
  assert.doesNotMatch(tabs, /setTimeout\(\(\) => saveTab\(tab\), 800\)/)
})

test('dirty external changes are tracked and require overwrite confirmation', () => {
  const tabs = read('src/renderer/tabs.js')

  assert.match(tabs, /handleExternalFileChange/)
  assert.match(tabs, /externalConflict/)
  assert.match(tabs, /externalContent/)
  assert.match(tabs, /confirm\(/)
  assert.match(tabs, /confirmOverwrite/)
  assert.match(tabs, /External changes detected/)
})

test('external conflicts expose explicit reload and overwrite actions', () => {
  const tabs = read('src/renderer/tabs.js')

  assert.match(tabs, /reloadExternalChanges/)
  assert.match(tabs, /overwriteExternalChanges/)
  assert.match(tabs, /Reload from Disk/)
  assert.match(tabs, /Overwrite Disk/)
  assert.match(tabs, /External change/)
})

test('file watcher refreshes are batched instead of immediate per-event tree rebuilds', () => {
  const tabs = read('src/renderer/tabs.js')
  const shell = read('src/renderer/shell.js')
  const index = read('src/renderer/index.js')

  assert.match(tabs, /scheduleTreeRefresh/)
  assert.match(shell, /handleExternalFileChange/)
  assert.match(index, /handleExternalFileChange/)
  assert.doesNotMatch(shell, /onFileChange\(\(\{ event, path: p \}\) => \{\s*const tab[\s\S]*?_callbacks\.refreshTree\?\.\(\)\s*\}\)/)
})

test('sidebar resize updates CSS during drag and persists once on release', () => {
  const tabs = read('src/renderer/tabs.js')
  const rightPanel = read('src/renderer/right-panel.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(tabs, /function startSidebarResize/)
  assert.match(tabs, /requestAnimationFrame\(applyWidth\)/)
  assert.match(tabs, /style\.setProperty\('--sidebar-width'/)
  assert.match(tabs, /cancelAnimationFrame\(frame\)/)
  assert.match(tabs, /onUp[\s\S]*updateSetting\('sidebarWidth', pendingWidth\)/)
  assert.doesNotMatch(tabs, /onMove[\s\S]{0,220}updateSetting\('sidebarWidth'/)
  assert.match(rightPanel, /requestAnimationFrame\(applyWidth\)/)
  assert.match(rightPanel, /style\.setProperty\('--right-sidebar-width'/)
  assert.match(rightPanel, /cancelAnimationFrame\(frame\)/)
  assert.match(rightPanel, /onUp[\s\S]*localStorage\.setItem\('fjordmark-right-sidebar-width'/)
  assert.match(css, /\.sidebar-resizer\s*\{[\s\S]*background: transparent/)
  assert.match(css, /\.sidebar-resizer\s*\{[\s\S]*margin-left: -5px/)
  assert.match(css, /\.sidebar-resizer::before\s*\{[\s\S]*width: 1px/)
})

test('tag pane is a movable widget backed by the link index tag data', () => {
  const index = read('src/renderer/index.js')
  const tagsView = read('src/renderer/tags-view.js')
  const explorer = read('src/renderer/file-explorer-view.js')
  const tabs = read('src/renderer/tabs.js')
  const state = read('src/renderer/state.js')

  assert.match(index, /registerRightPanel\('tags'/)
  assert.match(index, /tagIcon\(\)/)
  assert.match(index, /onLinkIndexChange\(.*renderTagsPanel/s)
  assert.match(index, /mountTagsPanel\(openFile,[\s\S]*state\.tagFilter = null/)
  assert.match(tagsView, /getAllTagNames/)
  assert.match(tagsView, /getFilesForTag/)
  assert.match(tagsView, /buildTagsPanel/)
  assert.match(tagsView, /mountTagsPanel/)
  assert.match(tagsView, /tags-selection/)
  assert.match(tagsView, /data-action="clear-tag-filter"/)
  assert.match(state, /tagFilter: null/)
  assert.doesNotMatch(explorer, /file-explorer-filter/)
  assert.doesNotMatch(explorer, /clearTagFilter/)
  assert.match(tabs, /getFilesForTag\(state\.tagFilter\)/)
})

test('right sidebar widget tabs expose only honest visible hit targets', () => {
  const rightPanel = read('src/renderer/right-panel.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(rightPanel, /class="right-sidebar__tab/)
  assert.match(css, /\.right-sidebar__tabs\s*\{[\s\S]*cursor: default/)
  assert.match(css, /\.right-sidebar__tab\s*\{[\s\S]*width: 22px/)
  assert.match(css, /\.right-sidebar__tab\s*\{[\s\S]*flex: 0 0 22px/)
  assert.match(css, /\.right-sidebar__tab\s*\{[\s\S]*height: 22px/)
  assert.match(css, /\.right-sidebar__tab\s*\{[\s\S]*border: 1px solid var\(--surface-edge\)/)
  assert.match(css, /\.right-sidebar__tab\s*\{[\s\S]*cursor: default/)
  assert.match(css, /\.right-sidebar__tabs > :not\(\.right-sidebar__tab\)\s*\{[\s\S]*pointer-events: none/)
  assert.match(css, /\.right-sidebar__tab svg\s*\{[\s\S]*pointer-events: none/)
  assert.match(css, /\.right-sidebar__tab \*\s*\{[\s\S]*cursor: default/)
})

test('widgets use docked IDE pane chrome', () => {
  const rightPanel = read('src/renderer/right-panel.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(rightPanel, /widget__header-main/)
  assert.match(rightPanel, /widget__header-controls/)
  assert.match(rightPanel, /aria-label="Move widget"/)
  assert.match(rightPanel, /aria-label="Collapse widget"/)
  assert.match(rightPanel, /aria-label="Close widget"/)
  assert.match(rightPanel, /right-sidebar__tab-label/)
  assert.match(css, /\.widget--active/)
  assert.match(css, /\.widget__header-main/)
  assert.match(css, /\.widget__header-controls/)
  assert.match(css, /\.right-sidebar__tab-label/)
})

test('global brand rail owns the native window chrome above every column', () => {
  const shell = read('src/renderer/shell.js')
  const rightPanel = read('src/renderer/right-panel.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(css, /--brandrail-height:\s*44px/)
  assert.match(shell, /<div class="app" id="app">[\s\S]*<div class="brandrail" id="brandrail" data-tauri-drag-region="deep">[\s\S]*<div class="layout">/)
  assert.doesNotMatch(shell, /sidebar-drag-region/)
  assert.doesNotMatch(rightPanel, /right-sidebar__drag-region/)
  assert.match(shell, /<div class="editor-area">[\s\S]*<div class="statusbar">[\s\S]*\$\{buildRightPanelContainer\(\)\}/)
  assert.match(css, /\.layout\s*\{[\s\S]*min-height: 0/)
  assert.match(css, /\.editor-area\s*\{[\s\S]*min-height: 0/)
  assert.match(css, /\.brandrail\s*\{[\s\S]*height: var\(--brandrail-height\)/)
  assert.match(css, /\.brandrail\s*\{[\s\S]*width: 100%/)
  assert.match(css, /\.right-sidebar\s*\{[\s\S]*backdrop-filter: blur\(calc\(var\(--surface-blur\) \* 0\.72\)\)/)
})

test('right-panel mounts graph widgets after their DOM is committed', () => {
  const rightPanel = read('src/renderer/right-panel.js')
  const graphView = read('src/renderer/graph-view.js')
  const linkIndex = read('src/renderer/link-index.js')

  assert.match(rightPanel, /const pendingMounts = \[\]/)
  assert.match(rightPanel, /pendingMounts\.push\(hooks\)/)
  assert.match(rightPanel, /stack\.replaceChildren\(fragment\)[\s\S]*pendingMounts\.forEach/)
  assert.doesNotMatch(rightPanel, /requestAnimationFrame\(\(\) => hooks\.onMount/)
  assert.match(graphView, /resolveWikilink/)
  assert.match(graphView, /targetPath = resolveWikilink/)
  assert.match(linkIndex, /normalizeWikilinkTarget/)
  assert.match(linkIndex, /\.split\('#'\)/)
  assert.match(linkIndex, /normalizedPath/)
})

test('settings exposes editable hotkeys with conflict-aware capture and reset', () => {
  const shell = read('src/renderer/shell.js')
  const keybindings = read('src/renderer/keybindings.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(shell, /\{ id: 'shortcuts', label: 'Shortcuts' \}/)
  assert.match(shell, /getAllBindings\(\)/)
  assert.match(shell, /data-keybinding-capture/)
  assert.match(shell, /data-keybinding-reset/)
  assert.match(shell, /findConflict\(/)
  assert.match(keybindings, /export function formatKeyEvent/)
  assert.match(css, /\.keybinding-list/)
})

test('frontmatter can be hidden in rendered document modes and drive a banner image', () => {
  const settings = read('src/renderer/settings.js')
  const shell = read('src/renderer/shell.js')
  const markdown = read('src/renderer/markdown.js')
  const preview = read('src/renderer/preview.js')
  const commands = read('src/renderer/commands.js')
  const tabs = read('src/renderer/tabs.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(settings, /hideFrontmatterInRenderedModes: true/)
  assert.match(settings, /showDocumentBanners: true/)
  assert.match(shell, /renderToggleSetting\('hideFrontmatterInRenderedModes'/)
  assert.match(shell, /renderToggleSetting\('showDocumentBanners'/)
  assert.match(shell, /refreshRenderedDocuments/)
  assert.match(markdown, /export function parseFrontmatterBlock/)
  assert.match(markdown, /export function getRenderableMarkdown/)
  assert.match(markdown, /export function mergeFrontmatterWithBody/)
  assert.match(markdown, /showDocumentBanners/)
  assert.match(markdown, /renderDocumentBanner/)
  assert.match(markdown, /document-banner/)
  assert.match(preview, /renderMarkdown\(markdown,[\s\S]*currentFilePath: activeTab\?\.path/)
  assert.match(preview, /showDocumentBanners: settings\.showDocumentBanners/)
  assert.match(commands, /getRenderableMarkdown\(tab\.content/)
  assert.match(commands, /mergeFrontmatterWithBody\(tab\.content/)
  assert.match(tabs, /mergeFrontmatterWithBody\(tab\.content/)
  assert.match(css, /\.document-banner\s*\{/)
  assert.match(css, /\.document-banner__image\s*\{/)
})

test('properties panel exposes focused banner controls backed by frontmatter', () => {
  const properties = read('src/renderer/properties-view.js')
  const index = read('src/renderer/index.js')
  const rightPanel = read('src/renderer/right-panel.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(index, /registerRightPanel\('properties'[\s\S]*defaultSide: 'left'/)
  assert.match(index, /registerRightPanel\('properties'[\s\S]*defaultActive: true/)
  assert.match(rightPanel, /hooks\?\.defaultSide === 'left'/)
  assert.match(properties, /renderBannerSettings/)
  assert.match(properties, /class="banner-settings"/)
  assert.match(properties, /id="banner-image-input"/)
  assert.match(properties, /data-banner-axis="banner_x"/)
  assert.match(properties, /data-banner-axis="banner_y"/)
  assert.match(properties, /data-action="apply-banner"/)
  assert.match(properties, /data-action="clear-banner"/)
  assert.match(properties, /updateBannerSettings/)
  assert.match(properties, /banner_x/)
  assert.match(properties, /banner_y/)
  assert.match(css, /\.banner-settings\s*\{/)
  assert.match(css, /\.banner-settings__preview\s*\{/)
  assert.match(css, /\.banner-settings__range\s*\{/)
})

test('welcome screen supports pinned workspaces managed from settings', () => {
  const recent = read('src/renderer/recent-projects.js')
  const shell = read('src/renderer/shell.js')
  const tabs = read('src/renderer/tabs.js')
  const index = read('src/renderer/index.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(recent, /PINNED_STORAGE_KEY/)
  assert.match(recent, /export function getPinnedProjects/)
  assert.match(recent, /export function togglePinnedProject/)
  assert.match(recent, /renderPinnedProjectsHtml/)
  assert.match(shell, /\{ id: 'workspace', label: 'Workspace' \}/)
  assert.match(shell, /data-settings-section="workspace"/)
  assert.match(shell, /Pinned workspaces/)
  assert.match(shell, /data-open-path/)
  assert.match(shell, /data-open-new-path/)
  assert.match(shell, /data-unpin-path/)
  assert.match(shell, /attachWelcomeProjectHandlers/)
  assert.match(tabs, /attachWelcomeProjectHandlers/)
  assert.match(tabs, /window\.fjord\?\.newWindow\?\.\(folderPath\)/)
  assert.match(index, /openWorkspaceInNewWindow/)
  assert.match(css, /\.pinned-list/)
  assert.match(css, /\.pinned-item__actions/)
  assert.match(css, /\.recent-pin/)
})

test('quick open includes heading matches and opens selected headings by line', () => {
  const palette = read('src/renderer/command-palette.js')
  const tabs = read('src/renderer/tabs.js')

  assert.match(palette, /extractHeadings/)
  assert.match(palette, /type: 'heading'/)
  assert.match(palette, /heading:\s*\{/)
  assert.match(palette, /openFile\(\{ path: result\.item\.path, name: result\.item\.name, heading: result\.item\.heading \}\)/)
  assert.match(tabs, /jumpToLine/)
  assert.match(tabs, /item\.heading\.line/)
})

test('desktop shell is a Tauri app rather than Electron', () => {
  const pkg = JSON.parse(read('package.json'))
  const tauriConfig = read('src-tauri/tauri.conf.json')
  const cargo = read('src-tauri/Cargo.toml')

  assert.equal(pkg.name, 'rista')
  assert.equal(pkg.scripts.dev, 'tauri dev')
  assert.equal(pkg.scripts.package, 'tauri build --bundles app && node scripts/fix-macos-bundle-icon.js')
  assert.ok(pkg.devDependencies['@tauri-apps/cli'])
  assert.ok(pkg.dependencies['@tauri-apps/api'])
  assert.ok(!pkg.devDependencies.electron)
  assert.ok(!pkg.devDependencies['electron-builder'])
  assert.ok(!pkg.dependencies['electron-updater'])
  assert.match(tauriConfig, /"productName": "Rísta"/)
  assert.match(tauriConfig, /"identifier": "app\.rista\.desktop"/)
  assert.match(tauriConfig, /"frontendDist": "\.\.\/dist\/app"/)
  assert.match(cargo, /tauri =/)
  assert.match(cargo, /notify =/)
})

test('renderer installs the Tauri-backed window.fjord compatibility API', () => {
  const index = read('src/renderer/index.js')
  const adapter = read('src/renderer/tauri-api.js')

  assert.match(index, /import '\.\/tauri-api\.js'/)
  assert.match(adapter, /from '@tauri-apps\/api\/core'/)
  assert.match(adapter, /from '@tauri-apps\/api\/event'/)
  assert.match(adapter, /window\.fjord =/)
  assert.match(adapter, /openFolder/)
  assert.match(adapter, /readFolder/)
  assert.match(adapter, /watchFolder/)
  assert.match(adapter, /onFileChange/)
  assert.match(adapter, /onCommand/)
})

test('terminal exposes shell metadata and command run details', () => {
  const terminal = read('src/renderer/terminal-drawer.js')
  const adapter = read('src/renderer/tauri-api.js')
  const tauriMain = read('src-tauri/src/main.rs')
  const css = read('src/renderer/styles/main.css')

  assert.match(adapter, /getShellInfo: \(\) => invoke\('get_shell_info'\)/)
  assert.match(tauriMain, /fn get_shell_info/)
  assert.match(tauriMain, /durationMs/)
  assert.match(tauriMain, /fn terminal_shell/)
  assert.match(tauriMain, /std::env::var\("ComSpec"\)/)
  assert.match(tauriMain, /unwrap_or\(-1\)/)
  assert.match(tauriMain, /let path = terminal_shell\(\)/)
  assert.match(terminal, /terminal-shell/)
  assert.match(terminal, /formatDuration/)
  assert.match(terminal, /terminal-quick-command/)
  assert.match(terminal, /typeof nextShellInfo\.name === 'string'/)
  assert.match(terminal, /terminal-line__meta/)
  assert.match(css, /\.terminal-shell/)
  assert.match(css, /\.terminal-line__meta/)
  assert.match(css, /\.terminal-quick-command/)
})

test('visible app identity is rebranded to Rista', () => {
  const html = read('public/index.html')
  const shell = read('src/renderer/shell.js')
  const state = read('src/renderer/state.js')
  const readme = read('README.md')

  assert.match(html, /<title>Rísta<\/title>/)
  assert.match(shell, /Rísta/)
  assert.doesNotMatch(shell, /fjord<span>mark<\/span>/)
  assert.match(state, /appMeta: \{ name: 'Rísta'/)
  assert.match(readme, /^# Rísta/m)
  assert.match(readme, /Tauri/)
  assert.doesNotMatch(readme, /Electron 29/)
})

test('Tauri uses native macOS overlay chrome with app-owned branding', () => {
  const tauriConfig = read('src-tauri/tauri.conf.json')
  const shell = read('src/renderer/shell.js')
  const css = read('src/renderer/styles/main.css')
  const adapter = read('src/renderer/tauri-api.js')
  const capability = read('src-tauri/capabilities/default.json')
  const tauriMain = read('src-tauri/src/main.rs')
  const infoPlist = read('src-tauri/Info.plist')

  assert.match(tauriConfig, /"label": "main"/)
  assert.match(tauriConfig, /"url": "index\.html"/)
  assert.match(tauriConfig, /"decorations": true/)
  assert.match(tauriConfig, /"shadow": true/)
  assert.match(tauriConfig, /"transparent": false/)
  assert.match(tauriConfig, /"titleBarStyle": "Overlay"/)
  assert.match(tauriConfig, /"hiddenTitle": true/)
  assert.match(tauriConfig, /"trafficLightPosition": \{\s*"x": 15,\s*"y": 17\s*\}/)
  assert.doesNotMatch(shell, /titlebar__spacer/)
  assert.doesNotMatch(shell, /window-control/)
  assert.doesNotMatch(shell, /data-window-action/)
  assert.match(shell, /handleWindowDragRegionMouseDown/)
  assert.doesNotMatch(shell, /addEventListener\('pointerdown', handleWindowDragRegionPointerDown\)/)
  assert.match(shell, /addEventListener\('mousedown', handleWindowDragRegionMouseDown\)/)
  assert.doesNotMatch(shell, /sidebar-drag-region/)
  assert.doesNotMatch(shell, /right-sidebar-drag-region/)
  assert.match(shell, /brandrail__workspace/)
  assert.match(shell, /brandrail-workspace-name/)
  assert.doesNotMatch(shell, /brandrail__mark/)
  assert.match(shell, /data-tauri-drag-region="deep"/)
  assert.match(css, /\.brandrail/)
  assert.match(css, /\.brandrail\s*\{[\s\S]*cursor: default/)
  assert.match(css, /\.brandrail\s*\{[\s\S]*user-select: none/)
  assert.match(css, /html, body, #root\s*\{[\s\S]*margin: 0/)
  assert.match(css, /\.brandrail__workspace/)
  assert.match(css, /left: 50%/)
  assert.match(css, /transform: translateX\(-50%\)/)
  assert.doesNotMatch(css, /\.window-control/)
  assert.match(adapter, /getCurrentWindow/)
  assert.match(adapter, /windowAction/)
  assert.match(adapter, /startWindowDrag/)
  assert.match(adapter, /invoke\('start_window_drag'\)/)
  assert.match(tauriMain, /fn start_window_drag\(window: tauri::Window\)/)
  assert.match(tauriMain, /RunEvent::Reopen/)
  assert.match(infoPlist, /NSQuitAlwaysKeepsWindows/)
  assert.match(capability, /core:window:allow-close/)
  assert.match(capability, /core:window:allow-minimize/)
  assert.match(capability, /core:window:allow-toggle-maximize/)
  assert.match(capability, /core:window:allow-start-dragging/)
  assert.match(capability, /"workspace-\*"/)
})

test('Tauri chrome positions Rista branding in the top overlay rail', () => {
  const shell = read('src/renderer/shell.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(shell, /syncWorkspaceChrome/)
  assert.match(shell, /brandrail__workspace-name/)
  assert.match(shell, /brandrail__workspace-path/)
  assert.doesNotMatch(shell, /brandrail__wordmark/)
  assert.doesNotMatch(shell, /local markdown, carved cleanly/)
  assert.doesNotMatch(css, /\.brandrail__mark/)
  assert.match(css, /\.brandrail__workspace-path/)
})

test('terminal drawer has workspace context and clear running states', () => {
  const terminal = read('src/renderer/terminal-drawer.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(terminal, /terminal-drawer__cwd/)
  assert.match(terminal, /terminal-drawer__status/)
  assert.match(terminal, /terminal-clear-btn/)
  assert.match(terminal, /setTerminalBusy/)
  assert.match(terminal, /Commands run in the current workspace folder/)
  assert.match(css, /\.terminal-drawer\.is-running \.terminal-drawer__status/)
  assert.match(css, /\.terminal-drawer__cwd/)
  assert.match(css, /\.terminal-drawer__action/)
})

test('AI chat queues destructive file edits into AI review instead of auto-writing', () => {
  const chat = read('src/renderer/ai-chat.js')
  const inspector = read('src/renderer/inspector.js')
  const review = read('src/renderer/ai-review.js')

  assert.match(chat, /queueAiReviewItem/)
  assert.match(chat, /Queued for review/)
  assert.match(inspector, /data-ai-review-action="accept"/)
  assert.match(inspector, /data-ai-review-action="reject"/)
  assert.match(review, /acceptAiReviewItem/)
  assert.match(review, /rejectAiReviewItem/)
  assert.match(review, /findConflictingReviewTab/)
  assert.match(review, /externalConflict/)
  assert.match(review, /dirty/)
  assert.match(review, /item\.error/)
})

test('agents sidebar stores local session metadata with status summaries', () => {
  const agents = read('src/renderer/agents-sidebar.js')
  const view = read('src/renderer/agents-view.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(agents, /\.fjordmark\/sessions/)
  assert.match(agents, /runtime/)
  assert.match(agents, /status/)
  assert.match(agents, /summary/)
  assert.match(agents, /agent-card__status/)
  assert.match(agents, /agent-card__summary/)
  assert.match(view, /Sessions are stored locally in your project/)
  assert.match(css, /\.agent-card__status/)
  assert.match(css, /\.agent-card__summary/)
})

test('project tree and preview support attachments plus spatial canvas and drawing docs', () => {
  const tauriMain = read('src-tauri/src/main.rs')
  const tabs = read('src/renderer/tabs.js')
  const previewPane = read('src/renderer/preview.js')
  const preview = read('src/renderer/attachment-preview.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(tauriMain, /\.fcanvas\.json/)
  assert.match(tauriMain, /\.fdraw\.json/)
  assert.match(tabs, /isSpatialFile/)
  assert.match(tabs, /isLikelyBinaryFile/)
  assert.match(tabs, /tab\.isAttachment \|\| tab\.isSpatial \|\| tab\.isBinary/)
  assert.match(previewPane, /resolveLocalPathFromHref/)
  assert.match(previewPane, /_wikilinkCallback\?\.\(targetPath\)/)
  assert.match(preview, /renderDrawingEditor/)
  assert.match(preview, /renderCanvasWorkspace/)
  assert.match(preview, /Preview is not available for this file type/)
  assert.match(css, /\.drawing-canvas/)
  assert.match(css, /\.canvas-board/)
})

test('canvas workspace can render and persist visual links between cards', () => {
  const preview = read('src/renderer/attachment-preview.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(preview, /data-action="add-link"/)
  assert.match(preview, /renderCanvasLinks/)
  assert.match(preview, /canvas-link-layer/)
  assert.match(preview, /doc\.links\.push/)
  assert.match(preview, /fromPath/)
  assert.match(preview, /toPath/)
  assert.match(css, /\.canvas-link-layer/)
  assert.match(css, /\.canvas-link/)
})

test('markdown preview can embed local drawing and canvas documents', () => {
  const markdown = read('src/renderer/markdown.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(markdown, /resolveSpatialEmbeds/)
  assert.match(markdown, /spatial-embed/)
  assert.match(markdown, /\.fdraw\.json/)
  assert.match(markdown, /\.fcanvas\.json/)
  assert.match(css, /\.spatial-embed/)
  assert.match(css, /\.spatial-embed__type/)
})

test('Tauri supports multiple windows and folder-specific watchers', () => {
  const adapter = read('src/renderer/tauri-api.js')
  const tauriMain = read('src-tauri/src/main.rs')
  const tabs = read('src/renderer/tabs.js')
  const index = read('src/renderer/index.js')

  assert.match(adapter, /file:new-window/)
  assert.match(adapter, /file:open-folder-new-window/)
  assert.match(adapter, /newWindow: \(folderPath = null, filePath = null\) => invoke\('new_window'/)
  assert.match(adapter, /openFolderInNewWindow/)
  assert.match(tauriMain, /async fn new_window/)
  assert.match(tauriMain, /WebviewWindowBuilder::new/)
  assert.match(tauriMain, /__RISTA_INITIAL_FOLDER__/)
  assert.match(tauriMain, /watchers: Mutex<HashMap<String, RecommendedWatcher>>/)
  assert.match(tauriMain, /fn watch_folder\(window: tauri::Window/)
  assert.match(tabs, /file:new-window/)
  assert.match(tabs, /changedPath\.startsWith\(state\.folderPath\)/)
  assert.match(index, /getInitialFolderPath/)
})

test('single markdown files open in simplified standalone windows', () => {
  const adapter = read('src/renderer/tauri-api.js')
  const tauriMain = read('src-tauri/src/main.rs')
  const tabs = read('src/renderer/tabs.js')
  const state = read('src/renderer/state.js')
  const shell = read('src/renderer/shell.js')
  const index = read('src/renderer/index.js')

  assert.match(state, /singleFilePath: null/)
  assert.match(adapter, /newWindow: \(folderPath = null, filePath = null\) => invoke\('new_window'/)
  assert.match(adapter, /launchFile: \(\) => invoke\('launch_file'\)/)
  assert.match(tauriMain, /launch_file/)
  assert.match(tauriMain, /async fn new_window\([\s\S]*app: tauri::AppHandle,[\s\S]*folder_path: Option<String>,[\s\S]*file_path: Option<String>,[\s\S]*\)/)
  assert.match(tauriMain, /__RISTA_INITIAL_FILE__/)
  assert.match(tauriMain, /RunEvent::Opened/)
  assert.match(tauriMain, /open_markdown_file_in_window/)
  assert.match(index, /getInitialFilePath/)
  assert.match(index, /openSingleFilePath\(initialFilePath/)
  assert.match(tabs, /export async function openSingleFilePath/)
  assert.match(tabs, /state\.singleFilePath = filePath/)
  assert.match(tabs, /state\.sidebarVisible = false/)
  assert.match(tabs, /state\.rightPanel = null/)
  assert.match(tabs, /window\.fjord\.watchFolder\?\.\(parentPath\(filePath\)\)/)
  assert.match(tabs, /changedPath !== state\.singleFilePath/)
  assert.match(shell, /state\.singleFilePath/)
  assert.match(shell, /Single file/)
})

test('widgets use pointer-driven repositioning instead of native HTML drag events', () => {
  const rightPanel = read('src/renderer/right-panel.js')

  assert.match(rightPanel, /data-action="widget-drag"/)
  assert.match(rightPanel, /function startWidgetDrag/)
  assert.match(rightPanel, /closest\('\.widget__header'\)/)
  assert.match(rightPanel, /toggleWidgetCollapse\(dragId\)/)
  assert.match(rightPanel, /pointermove/)
  assert.match(rightPanel, /onCancel/)
  assert.match(rightPanel, /finishDrag\(upEvent, false\)/)
  assert.match(rightPanel, /finishDrag\(cancelEvent, true\)/)
  assert.match(rightPanel, /elementFromPoint/)
  assert.doesNotMatch(rightPanel, /draggable="true"/)
  assert.doesNotMatch(rightPanel, /addEventListener\('dragstart'/)
})

test('app chrome is non-selectable while editing surfaces keep text selection', () => {
  const css = read('src/renderer/styles/main.css')

  assert.match(css, /body\s*\{[\s\S]*user-select: none/)
  assert.match(css, /\.cm-content,[\s\S]*user-select: text/)
  assert.match(css, /input,[\s\S]*textarea,[\s\S]*\[contenteditable="true"\][\s\S]*user-select: text/)
})

test('AI settings support expanded providers and safe local tool discovery', () => {
  const providers = read('src/renderer/ai-providers.js')
  const settings = read('src/renderer/settings.js')
  const shell = read('src/renderer/shell.js')
  const adapter = read('src/renderer/tauri-api.js')
  const tauriMain = read('src-tauri/src/main.rs')
  const actions = read('src/renderer/ai-actions.js')

  assert.match(providers, /openrouter/)
  assert.match(providers, /custom-openai-compatible/)
  assert.match(providers, /opencode-go/)
  assert.match(providers, /opencode-zen/)
  assert.match(providers, /openai: \{[\s\S]*transport: 'http'[\s\S]*apiKey: true[\s\S]*noApiKey: false[\s\S]*supportsTools: true[\s\S]*protocol: 'openai-compatible'/)
  assert.match(providers, /anthropic: \{[\s\S]*transport: 'http'[\s\S]*apiKey: true[\s\S]*noApiKey: false[\s\S]*supportsTools: true[\s\S]*protocol: 'anthropic'/)
  assert.match(providers, /openrouter: \{[\s\S]*transport: 'http'[\s\S]*apiKey: true[\s\S]*noApiKey: false[\s\S]*supportsTools: true[\s\S]*protocol: 'openai-compatible'/)
  assert.match(providers, /ollama: \{[\s\S]*transport: 'http'[\s\S]*apiKey: false[\s\S]*noApiKey: true[\s\S]*supportsTools: false[\s\S]*protocol: 'ollama'/)
  assert.match(providers, /'custom-openai-compatible': \{[\s\S]*transport: 'http'[\s\S]*apiKey: false[\s\S]*noApiKey: true[\s\S]*supportsTools: true[\s\S]*protocol: 'openai-compatible'/)
  assert.match(providers, /'opencode-go': \{[\s\S]*transport: 'cli'[\s\S]*apiKey: false[\s\S]*noApiKey: true[\s\S]*supportsTools: false[\s\S]*protocol: 'cli'/)
  assert.match(providers, /'opencode-zen': \{[\s\S]*transport: 'cli'[\s\S]*apiKey: false[\s\S]*noApiKey: true[\s\S]*supportsTools: false[\s\S]*protocol: 'cli'/)
  assert.match(settings, /assistantDock/)
  assert.match(shell, /data-settings-section="ai-tools"/)
  assert.match(shell, /renderLocalToolDiscovery/)
  assert.match(shell, /data-local-tool-refresh/)
  assert.match(adapter, /discoverLocalAiTools: \(\) => invoke\('discover_local_ai_tools'\)/)
  assert.match(tauriMain, /fn discover_local_ai_tools/)
  assert.match(tauriMain, /codex --version/)
  assert.match(tauriMain, /opencode --version/)
  assert.match(tauriMain, /version: None/)
  assert.match(tauriMain, /fn command_candidates/)
  assert.match(tauriMain, /fn is_executable_file/)
  assert.doesNotMatch(tauriMain, /arg\("--version"\)/)
  assert.doesNotMatch(tauriMain, /arg\("-lc"\)/)
  assert.match(tauriMain, /fn openai_messages/)
  assert.match(tauriMain, /tool_calls/)
  assert.match(tauriMain, /tool_call_id/)
  assert.match(tauriMain, /fn anthropic_messages/)
  assert.match(tauriMain, /tool_result/)
  assert.match(tauriMain, /tool_use_id/)
  assert.match(tauriMain, /fn anthropic_system/)
  assert.match(tauriMain, /payload\["system"\]/)
  assert.match(tauriMain, /pending_tool_results/)
  assert.match(tauriMain, /is_openai_compatible_key_provider/)
  assert.match(tauriMain, /tool_use/)
  assert.match(tauriMain, /toolCalls/)
  assert.match(actions, /apiKey: provider\.apiKey \? settings\.aiApiKey : ''/)
  assert.match(actions, /apiKey: config\.apiKey/)
  assert.match(read('src/renderer/ai-chat.js'), /apiKey: provider\.apiKey \? s\.aiApiKey : ''/)
  assert.match(tauriMain, /if !api_key\.is_empty\(\) && is_openai_compatible_key_provider\(provider\)/)
  assert.match(actions, /provider\.transport === 'cli'/)
  assert.match(actions, /Action transport will be wired in a later pass/)
})

test('assistant can dock as widget or dedicated side rail', () => {
  const settings = read('src/renderer/settings.js')
  const shell = read('src/renderer/shell.js')
  const index = read('src/renderer/index.js')
  const assistantRail = read('src/renderer/assistant-rail.js')
  const rightPanel = read('src/renderer/right-panel.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(settings, /ASSISTANT_DOCK_OPTIONS/)
  assert.match(settings, /right-rail/)
  assert.match(settings, /left-rail/)
  assert.match(settings, /right-sidebar/)
  assert.match(settings, /left-sidebar/)
  assert.match(shell, /renderSelectSetting\('assistantDock'/)
  assert.doesNotMatch(shell, /agent-card/)
  assert.doesNotMatch(shell, /openAgentSession/)
  assert.match(index, /function openAiChatSurface/)
  assert.match(index, /getSettings\(\)\.assistantDock/)
  assert.match(index, /mountAssistantRail\(\)/)
  assert.match(index, /openAssistantWidgetForDock\(dock\)/)
  assert.doesNotMatch(index, /buildAssistantRail/)
  assert.doesNotMatch(index, /mountAssistantRail\(\)\s*\nsyncAssistantRail\(\)/)
  assert.match(rightPanel, /export function moveWidgetToSide/)
  assert.match(rightPanel, /export function setWidgetSidePreference/)
  assert.match(assistantRail, /export function buildAssistantRail/)
  assert.match(assistantRail, /mountAssistantRail/)
  assert.match(assistantRail, /moveWidgetToSide/)
  assert.match(assistantRail, /setWidgetSidePreference/)
  assert.match(assistantRail, /closeRightPanel/)
  assert.match(assistantRail, /setWidgetSidePreference\('ai-chat', 'right'\)/)
  assert.match(assistantRail, /setWidgetSidePreference\('ai-chat', 'left'\)/)
  assert.match(assistantRail, /export function openAssistantWidgetForDock/)
  assert.match(assistantRail, /moveWidgetToSide\('ai-chat', 'right'\)/)
  assert.match(assistantRail, /moveWidgetToSide\('ai-chat', 'left'\)/)
  assert.match(assistantRail, /closeRightPanel\('ai-chat'\)/)
  assert.match(assistantRail, /body\.replaceChildren\(\)/)
  assert.match(assistantRail, /function applyAssistantDockPlacement/)
  assert.match(assistantRail, /applyAssistantDockPlacement\(dock\)[\s\S]*body\.innerHTML = buildAiChatPanel\(\)/)
  assert.ok(
    assistantRail.indexOf('applyAssistantDockPlacement(dock)') < assistantRail.indexOf('body.innerHTML = buildAiChatPanel()'),
    'assistant widget must close or move before rail chat DOM is injected'
  )
  assert.match(assistantRail, /assistant-rail/)
  assert.match(css, /\.assistant-rail/)
  assert.match(css, /\.assistant-rail\.open/)
})

test('right sidebar exposes wiki maintenance quality signals', () => {
  const index = read('src/renderer/index.js')
  const view = read('src/renderer/wiki-quality-view.js')
  const analyzer = read('src/renderer/wiki-quality.js')
  const icons = read('src/renderer/icons.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(index, /registerRightPanel\('wiki-quality'/)
  assert.match(index, /onLinkIndexChange\(\(\) => renderWikiQualityPanel\(\)\)/)
  assert.match(index, /handleWikiQualityPanelEvent/)
  assert.match(view, /export function buildWikiQualityPanel/)
  assert.match(view, /export function mountWikiQualityPanel/)
  assert.match(view, /export function renderWikiQualityPanel/)
  assert.match(view, /export function handleWikiQualityPanelEvent/)
  assert.match(analyzer, /export function analyzeWikiQuality/)
  assert.match(analyzer, /unresolvedLinks/)
  assert.match(analyzer, /orphanNotes/)
  assert.match(analyzer, /duplicateTitles/)
  assert.match(analyzer, /glossaryCandidates/)
  assert.match(icons, /export function wikiQualityIcon/)
  assert.match(css, /\.wiki-quality/)
  assert.match(css, /\.wiki-quality-row/)
})

test('markdown renderer documents and handles common Obsidian compatibility syntax', () => {
  const markdown = read('src/renderer/markdown.js')
  const css = read('src/renderer/styles/main.css')
  const readme = read('README.md')

  assert.match(markdown, /resolveObsidianEmbeds/)
  assert.match(markdown, /resolveBlockReferences/)
  assert.match(markdown, /data-callout-fold/)
  assert.match(markdown, /obsidian-embed--image/)
  assert.match(markdown, /block-ref-anchor/)
  assert.match(css, /\.obsidian-embed/)
  assert.match(css, /\.block-ref-anchor/)
  assert.match(readme, /Obsidian Compatibility/)
  assert.match(readme, /callouts/)
  assert.match(readme, /block references/)
})

test('right sidebar exposes related notes from the local semantic index', () => {
  const index = read('src/renderer/index.js')
  const view = read('src/renderer/related-notes-view.js')
  const semantic = read('src/renderer/semantic-index.js')
  const icons = read('src/renderer/icons.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(index, /registerRightPanel\('related-notes'/)
  assert.match(index, /onLinkIndexChange\(\(\) => renderRelatedNotesPanel\(\)\)/)
  assert.match(index, /handleRelatedNotesPanelEvent/)
  assert.match(view, /export function buildRelatedNotesPanel/)
  assert.match(view, /export function mountRelatedNotesPanel/)
  assert.match(view, /export function renderRelatedNotesPanel/)
  assert.match(view, /export function handleRelatedNotesPanelEvent/)
  assert.match(view, /catch \(err\)/)
  assert.match(view, /related-notes__error/)
  assert.match(semantic, /export function buildSemanticIndex/)
  assert.match(semantic, /export function searchSemanticIndex/)
  assert.match(semantic, /export function findRelatedNotes/)
  assert.match(semantic, /relevance/)
  assert.match(semantic, /snippet/)
  assert.match(icons, /export function relatedNotesIcon/)
  assert.match(css, /\.related-notes/)
  assert.match(css, /\.related-notes__error/)
})

test('project search blends local semantic citations with file matches', () => {
  const search = read('src/renderer/search-panel.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(search, /buildSemanticIndex/)
  assert.match(search, /searchSemanticIndex/)
  assert.match(search, /try \{[\s\S]*buildSemanticIndex/)
  assert.match(search, /catch \(err\)/)
  assert.match(search, /searchIndexError/)
  assert.match(search, /mergeSearchResults/)
  assert.match(search, /search-result__cite/)
  assert.match(search, /notes indexed/)
  assert.match(search, /Index error/)
  assert.match(css, /\.search-result__cite/)
})

test('semantic search citations open the cited heading line', () => {
  const search = read('src/renderer/search-panel.js')
  const workspace = read('src/renderer/workspace.js')

  assert.match(search, /data-line="\$\{escapeAttr\(r\.line/)
  assert.match(search, /function buildOpenTarget/)
  assert.match(search, /heading: \{ text: result\.heading, line: Number\(result\.line\)/)
  assert.match(search, /callback\?\.\(buildOpenTarget\(result\)\)/)
  assert.match(workspace, /typeof target === 'string'/)
  assert.match(workspace, /_callbacks\.openFile\?\.\(target\)/)
})

test('wiki quality findings can create missing notes and be dismissed', () => {
  const view = read('src/renderer/wiki-quality-view.js')
  const analyzer = read('src/renderer/wiki-quality.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(view, /data-action="create-missing-note"/)
  assert.match(view, /data-action="dismiss-finding"/)
  assert.match(view, /createMissingNoteFromFinding/)
  assert.match(view, /dismissWikiQualityFinding/)
  assert.match(view, /localStorage/)
  assert.match(analyzer, /export function wikiQualityFindingKey/)
  assert.match(analyzer, /nearDuplicateNotes/)
  assert.match(css, /\.wiki-quality-row__actions/)
})

test('source-aware AI editor actions queue review items with citations', () => {
  const actions = read('src/renderer/ai-actions.js')
  const review = read('src/renderer/ai-review.js')
  const inspector = read('src/renderer/inspector.js')
  const css = read('src/renderer/styles/main.css')

  assert.match(actions, /SOURCE_AWARE_AI_ACTIONS/)
  assert.match(actions, /suggest-tags/)
  assert.match(actions, /suggest-aliases/)
  assert.match(actions, /suggest-properties/)
  assert.match(actions, /extract-tasks/)
  assert.match(actions, /buildSourceContext/)
  assert.match(actions, /queueAiReviewItem/)
  assert.match(actions, /sourceNotes/)
  assert.match(actions, /relativeProjectPath/)
  assert.doesNotMatch(actions, /view\.dispatch\(\{\s*changes: \{ from, to, insert: text \}/)
  assert.match(review, /sourceNotes/)
  assert.match(inspector, /ai-review-item__source/)
  assert.match(css, /\.ai-review-item__source/)
})

test('CSP enforces local-only origins (zero external network calls)', () => {
  const html = read('public/index.html')
  
  // Extract CSP content from meta tag
  const cspMatch = html.match(/meta http-equiv="Content-Security-Policy"\s+content="([^"]+)"/)
  assert.ok(cspMatch, 'CSP meta tag must exist')
  
  const cspValue = cspMatch[1]
  
  // Verify default-src is restricted to self
  assert.match(cspValue, /default-src 'self'/, 'default-src must be restricted to self')
  
  // Verify font-src is restricted to self (no Google Fonts CDN)
  assert.match(cspValue, /font-src 'self'/, 'font-src must be restricted to self')
  
  // Verify connect-src is either absent or also restricted
  if (cspValue.includes('connect-src')) {
    assert.match(cspValue, /connect-src 'self'/, 'if connect-src is set, it must be self only')
  }
  
  // Verify no external URLs in CSP value (no https:// or http:// except localhost)
  const externalUrls = cspValue.match(/https?:\/\/(?!localhost)[^\s;]/g)
  assert.strictEqual(externalUrls, null, `CSP must not contain external URLs, found: ${externalUrls}`)
})

test('HTML has no external CDN script or font tags', () => {
  const html = read('public/index.html')
  
  // No Google Fonts link
  assert.doesNotMatch(html, /fonts\.googleapis\.com/, 'HTML must not load Google Fonts')
  
  // No Google Fonts script
  assert.doesNotMatch(html, /scripts\.font\.is/, 'HTML must not load font services')
  
  // No other common CDN links in HTML
  assert.doesNotMatch(html, /cdnjs\.com/, 'HTML must not load from cdnjs')
  assert.doesNotMatch(html, /unpkg\.com/, 'HTML must not load from unpkg')
  assert.doesNotMatch(html, /jsdelivr\.net/, 'HTML must not load from jsdelivr')
  
  // Verify all stylesheet links are local
  const styleLinks = html.match(/<link[^>]*rel="stylesheet"[^>]*href="([^"]+)"/g) || []
  styleLinks.forEach(link => {
    const href = link.match(/href="([^"]+)"/)[1]
    assert.doesNotMatch(href, /^https?:\/\//, `Stylesheet link must be relative: ${href}`)
  })
})

test('fonts.css loads only self-hosted fonts (no CDN imports)', () => {
  const fontsCss = read('public/fonts.css')
  
  // Verify no @import from external URLs
  assert.doesNotMatch(fontsCss, /@import\s+url\(['"]?https?:/, 'fonts.css must not import from CDN')
  assert.doesNotMatch(fontsCss, /fonts\.googleapis\.com/, 'fonts.css must not import from Google Fonts')
  
  // Verify all @import paths are local relative paths
  const imports = fontsCss.match(/@import\s+['"]([^'"]+)['"]/g) || []
  imports.forEach(imp => {
    const path = imp.match(/@import\s+['"]([^'"]+)['"]/)[1]
    assert.match(path, /^\.\/fonts\//, `Font import must use local relative path: ${path}`)
  })
})

async function importPerfBudgetModule() {
  const source = fs.readFileSync(path.join(root, 'src/renderer/perf-budget.js'), 'utf8')
  const modulePath = path.join(root, `.tmp-perf-budget-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}.mjs`)
  fs.writeFileSync(modulePath, source)
  try {
    return await import(`file://${modulePath}`)
  } finally {
    fs.rmSync(modulePath, { force: true })
  }
}

test('perf budget constants are defined with correct values', async () => {
  const { LAUNCH_BUDGET_MS, FILE_SWITCH_BUDGET_MS } = await importPerfBudgetModule()

  assert.equal(LAUNCH_BUDGET_MS, 400, 'LAUNCH_BUDGET_MS should be 400ms')
  assert.equal(FILE_SWITCH_BUDGET_MS, 80, 'FILE_SWITCH_BUDGET_MS should be 80ms')
})

test('perf budget module exports instrumentation functions', async () => {
  const perfBudget = await importPerfBudgetModule()

  assert.equal(typeof perfBudget.markLaunchStart, 'function', 'markLaunchStart should be exported')
  assert.equal(typeof perfBudget.markLaunchDone, 'function', 'markLaunchDone should be exported')
  assert.equal(typeof perfBudget.markFileSwitchStart, 'function', 'markFileSwitchStart should be exported')
  assert.equal(typeof perfBudget.markFileSwitchDone, 'function', 'markFileSwitchDone should be exported')
  assert.equal(typeof perfBudget.measureFileSwitch, 'function', 'measureFileSwitch should be exported')
})

test('measureFileSwitch function wraps and returns result', async () => {
  const { measureFileSwitch } = await importPerfBudgetModule()

  const testValue = 42
  const result = measureFileSwitch(() => testValue)

  assert.equal(result, testValue, 'measureFileSwitch should return the function result')
})
